platform :ios, '10.0'


target 'Mia_Example' do
    use_frameworks!
    
    pod 'Alamofire'
    pod 'BNHtmlPdfKit', :git => 'https://github.com/brentnycum/BNHtmlPdfKit'
    
    pod 'Mia', :path => '../'
    
    
    #pod 'ChameleonFramework/Swift' # throws errors. check later
    pod 'DynamicColor'
    pod 'RandomColorSwift'
    
    
    target 'Mia_ExampleTests' do
        inherit! :search_paths
    end
end
