platform :ios, '10.0'


target 'Mia_Example' do
    use_frameworks!

    pod 'Mia', :path => '../'

#    pod 'PageMenu'
#    pod 'MediumMenu'
#    pod 'JBDatePicker'
    

    
    
    target 'Mia_ExampleTests' do
        inherit! :search_paths
    end
    
    
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MIA'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
end
