platform :ios, '10.0'


target 'Mia_Example' do
    use_frameworks!
    pod 'SwiftLint'
    pod 'Mia', :path => '../'

    pod 'PageMenu'
    pod 'MediumMenu'
    pod 'JBDatePicker'
    
    
    pod 'UIDeviceComplete'
    pod 'Luminous'
    pod 'DeviceKit'

    
    
    
    
    target 'Mia_ExampleTests' do
        inherit! :search_paths
    end
end
