# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --repo-update --project-directory=Example
script:
- pod lib lint --quick
- cd Example
- xcodebuild -workspace Mia.xcworkspace -scheme Mia-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' -enableCodeCoverage YES  build test
after_success:
- bash <(curl -s https://codecov.io/bash)
